name = "btd6-index-site"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[hyperdrive]]
binding = "BTD6_INDEX_DB"
id = "c8312296d04b483ea37c8edd34a32ce6"
# You need to configure your Hyperdrive connection separately
# This will be configured via: wrangler hyperdrive create <name> --connection-string=<postgres-connection-string>

[[r2_buckets]]
binding = 'BTD6_INDEX_MEDIA'
bucket_name = 'btd6index'
preview_bucket_name = 'btd6indexpreview'
