[[d1_databases]]
binding = "BTD6_INDEX_DB"
database_name = "btd6index"
database_id = "10ae7575-0381-46c6-a1ea-964acef749d9"

[[r2_buckets]]
binding = 'BTD6_INDEX_MEDIA'
bucket_name = 'btd6index'
preview_bucket_name = 'btd6indexpreview'