compatibility_date = "2026-08-04"

[[hyperdrive]]
binding = "BTD6_INDEX_DB"
id = "btd6-index-hyperdrive"
# You need to configure your Hyperdrive connection separately
# This will be configured via: wrangler hyperdrive create <name> --connection-string=<postgres-connection-string>

[[r2_buckets]]
binding = 'BTD6_INDEX_MEDIA'
bucket_name = 'btd6index'
preview_bucket_name = 'btd6indexpreview'
